import type {WriteSessionView} from './longmemeval_adapter.js';import type {ExtractedFact,FactKind,LocalChatRequest,LocalDependencies} from './local_memory_v2.js';
export const EXTRACTION_V6_PROMPT=`Select only memory-relevant autobiographical claims explicitly asserted by the USER. Candidate text is immutable user text; never add or rewrite facts.

Select a candidate only when it contains a claim about the user, the user's own life, or a person/object directly connected to the user's life. Do not select public/company/general facts supplied by the assistant, a question's unknown answer, generic requests for advice, or conversational reactions such as thanks, "interesting", "good to hear", and hopes about an unrelated third party. Assistant turns are context only for resolving what a user's reply refers to.

Assign kind precisely:
- current: a confirmed present state, enduring preference, possession, role, or ongoing activity.
- historical: a completed past event or former state. A past event is NOT retracted.
- tentative: considering, maybe, aiming, intending, planning, or a future action that has not yet occurred. Definite-sounding future plans remain tentative until completed.
- retracted: only an explicit cancellation, withdrawal, correction, denial, or request to forget a previously held fact. Never use retracted merely because something happened in the past.

Return selected claim IDs and kinds only. If no candidate qualifies, return {"selections":[]}. Empty output is normal and preferable to unsupported or transient memory.`;
export interface ClaimCandidate{claim_id:string;turn_index:number;text:string}
export interface ExtractionV6Result{facts:ExtractedFact[];selected_claims:{claim_id:string;turn_index:number;verbatim_text:string;kind:FactKind}[];candidates:ClaimCandidate[]}
export function userClaimCandidates(session:WriteSessionView):ClaimCandidate[]{const out:ClaimCandidate[]=[];for(let ti=0;ti<session.turns.length;ti++){const t=session.turns[ti];if(t.role!=='user')continue;const pieces=t.content.split(/(?<=[.!?])\s+(?=[A-Z"'])|\n+/).map(x=>x.trim()).filter(Boolean);for(let pi=0;pi<pieces.length;pi++)out.push({claim_id:`U${ti}S${pi}`,turn_index:ti,text:pieces[pi]});}return out;}
function schema(ids:string[]){return {type:'object',additionalProperties:false,required:['selections'],properties:{selections:{type:'array',items:{type:'object',additionalProperties:false,required:['claim_id','kind'],properties:{claim_id:{type:'string',enum:ids},kind:{type:'string',enum:['current','historical','tentative','retracted']}}}}}}};
export async function extractSessionV6(session:WriteSessionView,deps:LocalDependencies):Promise<ExtractionV6Result>{const candidates=userClaimCandidates(session),context=session.turns.map((t,index)=>({index,role:t.role,content:t.content}));const req:LocalChatRequest={stage:'extraction',model:'Qwen3-8B',temperature:0,max_tokens:2048,chat_template_kwargs:{enable_thinking:false},messages:[{role:'system',content:EXTRACTION_V6_PROMPT},{role:'user',content:JSON.stringify({timestamp:session.timestamp,candidates,conversation_context:context})}],response_format:{type:'json_schema',json_schema:{name:'phase4_extraction_v6',strict:true,schema:schema(candidates.map(c=>c.claim_id))}}};let o:any;try{o=JSON.parse(await deps.chat(req));}catch{throw Error('Extraction v6 rejected: invalid JSON');}if(!o||Object.keys(o).join(',')!=='selections'||!Array.isArray(o.selections))throw Error('Extraction v6 rejected: invalid envelope');const byId=new Map(candidates.map(c=>[c.claim_id,c])),seen=new Set<string>(),facts:ExtractedFact[]=[],selected_claims:ExtractionV6Result['selected_claims']=[];for(const s of o.selections){if(!s||Object.keys(s).sort().join(',')!=='claim_id,kind'||typeof s.claim_id!=='string'||!['current','historical','tentative','retracted'].includes(s.kind)||!byId.has(s.claim_id))throw Error('Extraction v6 rejected: invalid selection');if(seen.has(s.claim_id))continue;seen.add(s.claim_id);const c=byId.get(s.claim_id)!;if(!session.turns[c.turn_index].content.includes(c.text))throw Error('Extraction v6 internal verbatim invariant failed');facts.push({text:c.text,kind:s.kind,source_turns:[c.turn_index]});selected_claims.push({...c,verbatim_text:c.text,kind:s.kind});}return {facts,selected_claims,candidates};}
