import type{WriteSessionView}from'./longmemeval_adapter.js';import type{ExtractedFact,FactKind,LocalChatRequest,LocalDependencies}from'./local_memory_v2.js';import{extractSessionV6,EXTRACTION_V6_PROMPT}from'./local_extractor_v6.js';
export const EXTRACTION_V8_VERIFIER_PROMPT=`You are the faithfulness gate for user memory extraction. For every immutable user-text candidate, return exactly one verdict: current, historical, tentative, retracted, or DROP.

Keep only a claim genuinely asserted as the USER's own information, or information about a person/object directly connected to the user's life, and useful as autobiographical evidence. DROP pure questions, advice requests, thanks/reactions, generic topical interest, assistant-supplied answers, and quotations/pasted material attributed to someone else. In particular, first-person text followed by another person's signature (for example "... – Janelle") is that person's testimonial, not the user's memory. A resume or bio explicitly introduced by the user as "my bio" is user information and may be kept.

Kinds: current = confirmed present/enduring/ongoing; historical = completed past; tentative = any uncompleted plan/intention/aim/option/consideration, including "I will", "I'm going to", "planning", and "thinking of"; retracted = only explicit cancellation, withdrawal, correction, denial, or request to forget. Past never means retracted. Judge only supplied text and context; do not fill in a question's answer.`;
export interface ExtractionV8Result{facts:ExtractedFact[];proposal_count:number;verdicts:{claim_id:string;verdict:FactKind|'DROP';text:string;turn_index:number}[]}
function verdictSchema(ids:string[]){return{type:'object',additionalProperties:false,required:ids,properties:Object.fromEntries(ids.map(id=>[id,{type:'string',enum:['current','historical','tentative','retracted','DROP']}]))};}
export async function extractSessionV8(session:WriteSessionView,deps:LocalDependencies):Promise<ExtractionV8Result>{const proposed=await extractSessionV6(session,deps);if(!proposed.selected_claims.length)return{facts:[],proposal_count:0,verdicts:[]};const items=proposed.selected_claims.map(c=>({claim_id:c.claim_id,verbatim_user_text:c.verbatim_text,full_user_turn:session.turns[c.turn_index].content,preceding_assistant_context:c.turn_index>0&&session.turns[c.turn_index-1].role==='assistant'?session.turns[c.turn_index-1].content.slice(-1200):null}));const ids=items.map(x=>x.claim_id),req:LocalChatRequest={stage:'extraction',model:'Qwen3-8B',temperature:0,max_tokens:2048,chat_template_kwargs:{enable_thinking:false},messages:[{role:'system',content:EXTRACTION_V8_VERIFIER_PROMPT},{role:'user',content:JSON.stringify({items})}],response_format:{type:'json_schema',json_schema:{name:'phase4_extraction_v8_verdicts',strict:true,schema:verdictSchema(ids)}}};let o:any;try{o=JSON.parse(await deps.chat(req));}catch{throw Error('Extraction v8 verifier rejected: invalid JSON');}if(!o||Object.keys(o).sort().join(',')!==[...ids].sort().join(','))throw Error('Extraction v8 verifier rejected: missing/extra verdict');const facts:ExtractedFact[]=[],verdicts:ExtractionV8Result['verdicts']=[];for(const c of proposed.selected_claims){const verdict=o[c.claim_id] as FactKind|'DROP';if(!['current','historical','tentative','retracted','DROP'].includes(verdict))throw Error('Extraction v8 verifier rejected: invalid verdict');verdicts.push({claim_id:c.claim_id,verdict,text:c.verbatim_text,turn_index:c.turn_index});if(verdict!=='DROP')facts.push({text:c.verbatim_text,kind:verdict,source_turns:[c.turn_index]});}return{facts,proposal_count:proposed.selected_claims.length,verdicts};}
export{EXTRACTION_V6_PROMPT};
