import type{WriteSessionView}from'./longmemeval_adapter.js';import type{ExtractedFact,FactKind,LocalChatRequest,LocalDependencies}from'./local_memory_v2.js';import{userClaimCandidates,type ClaimCandidate}from'./local_extractor_v6.js';
export const EXTRACTION_V10_PROMPT=`For each immutable USER excerpt, classify it as current, historical, tentative, retracted, or DROP. Think carefully about authorship, completion state, and persistence. Return one verdict for every ID.

KEEP only autobiographical information genuinely asserted by the user: the user's life, preferences, possessions, role, completed experiences, ongoing state, or people/objects directly connected to the user. DROP pure questions, requests with no personal fact, greetings/thanks/reactions, generic topical interest, assistant-provided facts, and pasted/quoted text attributed to other people. First-person testimonials followed by another person's signature are not the user's memories. A resume explicitly introduced as "my bio" is user information.

KIND RULES:
- historical = any completed event/action or former state, even if it happened just now or recently. "I finished", "I bought", "I went", "I attended", "I was prescribed", and "I just completed" are historical, never current.
- tentative = every uncompleted future plan, intention, aim, option, or consideration: "I will", "I'll", "I'm going to", "planning", "thinking of", "might", or "want to".
- current = a confirmed present/enduring state, possession, role, preference, or genuinely ongoing activity.
- retracted = only an explicit cancellation, withdrawal, correction, denial, or request to forget. Past is never retracted.

Do not infer an answer from a question and do not rewrite text. End with exactly one compact JSON object {"verdicts":{"ID":"current|historical|tentative|retracted|DROP"}} containing every supplied ID and no text after it.`;
export interface ExtractionV10Result{facts:ExtractedFact[];verdicts:{claim_id:string;verdict:FactKind|'DROP';text:string;turn_index:number}[];prefiltered:{claim_id:string;reason:string}[];candidate_count:number}
function prefilter(c:ClaimCandidate):string|null{const t=c.text.trim();if(/^(?:do|does|did|can|could|would|should|what|why|where|when|who|which|is|are|was|were|have|has|how)\b/i.test(t)&&t.endsWith('?'))return'pure_interrogative';if(/^you\b/i.test(t))return'non_user_subject';if(/^(?:thanks?|thank you|that(?:'s| is) (?:helpful|great|good|interesting)|interesting|good to (?:know|hear)|i see)[!.]*$/i.test(t))return'conversation_only';return null;}
function finalJson(content:string):any{const start=content.lastIndexOf('{"verdicts"');if(start<0)throw Error('Extraction v10 verifier missing final JSON');const tail=content.slice(start).trim();try{return JSON.parse(tail);}catch{throw Error('Extraction v10 verifier invalid final JSON');}}
export async function extractSessionV10(session:WriteSessionView,deps:LocalDependencies):Promise<ExtractionV10Result>{const all=userClaimCandidates(session),prefiltered=all.flatMap(c=>{const reason=prefilter(c);return reason?[{claim_id:c.claim_id,reason}]:[]}),blocked=new Set(prefiltered.map(x=>x.claim_id)),candidates=all.filter(c=>!blocked.has(c.claim_id)),verdicts:ExtractionV10Result['verdicts']=[],facts:ExtractedFact[]=[];for(let offset=0;offset<candidates.length;offset+=25){const batch=candidates.slice(offset,offset+25),turnIds=[...new Set(batch.map(x=>x.turn_index))],user_turns=turnIds.map(turn_index=>({turn_index,content:session.turns[turn_index].content,preceding_assistant_context:turn_index>0&&session.turns[turn_index-1].role==='assistant'?session.turns[turn_index-1].content.slice(-1200):null})),items=batch.map(x=>({id:x.claim_id,turn_index:x.turn_index,text:x.text}));const req:LocalChatRequest={stage:'extraction',model:'Qwen3-8B',temperature:0,max_tokens:4096,chat_template_kwargs:{enable_thinking:true}as never,messages:[{role:'system',content:EXTRACTION_V10_PROMPT},{role:'user',content:JSON.stringify({items,user_turns})}],response_format:undefined as never};const content=await deps.chat(req),o=finalJson(content),ids=batch.map(x=>x.claim_id);if(!o||typeof o.verdicts!=='object'||Object.keys(o.verdicts).sort().join(',')!==[...ids].sort().join(','))throw Error('Extraction v10 verifier missing/extra verdict');for(const c of batch){const verdict=o.verdicts[c.claim_id]as FactKind|'DROP';if(!['current','historical','tentative','retracted','DROP'].includes(verdict))throw Error('Extraction v10 invalid verdict');verdicts.push({claim_id:c.claim_id,verdict,text:c.text,turn_index:c.turn_index});if(verdict!=='DROP')facts.push({text:c.text,kind:verdict,source_turns:[c.turn_index]});}}
 return{facts,verdicts,prefiltered,candidate_count:all.length};}
