import type {WriteSessionView} from './longmemeval_adapter.js';import type {ExtractedFact,FactKind,LocalChatRequest,LocalDependencies} from './local_memory_v2.js';
export {EXTRACTION_V4_PROMPT as EXTRACTION_V5_PROMPT} from './local_extractor_v4.js';import {EXTRACTION_V4_PROMPT} from './local_extractor_v4.js';
export interface ExtractionV5Result{facts:ExtractedFact[];verbatim_user_evidence:{fact_index:number;turns:{turn_index:number;content:string}[]}[]}
function schema(userIndexes:number[]){return {type:'object',additionalProperties:false,required:['facts'],properties:{facts:{type:'array',items:{type:'object',additionalProperties:false,required:['text','kind','source_turns'],properties:{text:{type:'string',minLength:1},kind:{type:'string',enum:['current','historical','tentative','retracted']},source_turns:{type:'array',minItems:1,items:{type:'integer',enum:userIndexes}}}}}}}};
export async function extractSessionV5(session:WriteSessionView,deps:LocalDependencies):Promise<ExtractionV5Result>{
 const users=session.turns.flatMap((t,i)=>t.role==='user'?[i]:[]),payload={timestamp:session.timestamp,turns:session.turns.map((t,index)=>({index,role:t.role,content:t.content}))};
 const req:LocalChatRequest={stage:'extraction',model:'Qwen3-8B',temperature:0,max_tokens:4096,chat_template_kwargs:{enable_thinking:false},messages:[{role:'system',content:EXTRACTION_V4_PROMPT},{role:'user',content:JSON.stringify(payload)}],response_format:{type:'json_schema',json_schema:{name:'phase4_extraction_v5',strict:true,schema:schema(users)}}};let o:any;try{o=JSON.parse(await deps.chat(req));}catch{throw Error('Extraction v5 rejected: invalid JSON');}
 if(!o||Object.keys(o).join(',')!=='facts'||!Array.isArray(o.facts))throw Error('Extraction v5 rejected: invalid envelope');const facts:ExtractedFact[]=[],verbatim_user_evidence:ExtractionV5Result['verbatim_user_evidence']=[];
 for(let i=0;i<o.facts.length;i++){const f=o.facts[i] as {text:string;kind:FactKind;source_turns:number[]};if(!f||Object.keys(f).sort().join(',')!=='kind,source_turns,text'||typeof f.text!=='string'||!f.text.trim()||!['current','historical','tentative','retracted'].includes(f.kind)||!Array.isArray(f.source_turns)||!f.source_turns.length||f.source_turns.some(x=>!Number.isInteger(x)||session.turns[x]?.role!=='user'))throw Error('Extraction v5 rejected: invalid fact/source');const ids=[...new Set(f.source_turns)];facts.push({text:f.text.trim(),kind:f.kind,source_turns:ids});verbatim_user_evidence.push({fact_index:i,turns:ids.map(turn_index=>({turn_index,content:session.turns[turn_index].content}))});}
 return {facts,verbatim_user_evidence};
}
