import assert from "node:assert/strict";
import {answerFromState, applyDecision, candidates, createMemoryState, extractSession, ingestFact, type ExtractedFact, type LocalChatRequest, type LocalDependencies} from "./local_memory_v2.js";
import {auditExtraction, auditRetrieval, auditWriter} from "./audit_local_memory_v2.js";

// Pure in-process fixtures: no network and no local inference.
const requests: LocalChatRequest[] = [];
let response = "";
const deps: LocalDependencies = {chat: async r => {requests.push(r); return response;}, embed: async texts => texts.map(() => [1, 0])};
const context = {session_index: 0, fact_index: 0, timestamp: "2025/01/01 (Wed) 10:00"};
const f: ExtractedFact = {text: "User lives in Shanghai and works remotely Friday.", kind: "current", source_turns: [0]};
response = JSON.stringify({facts: [f]});
const facts = await extractSession({timestamp: context.timestamp, turns: [{role: "user", content: f.text}]}, deps);
assert.deepEqual(facts, [f]);
assert.equal(requests[0].max_tokens, 4096);
assert.equal(requests[0].model, "Qwen3-8B");
assert.equal(requests[0].chat_template_kwargs.enable_thinking, false);
const initial = createMemoryState();
const archived = await ingestFact(initial, f, context, deps);
response = JSON.stringify({content: f.text});
const b = await applyDecision(archived, f, {operation: "ADD", target: "NONE"}, context, deps);
const c = structuredClone(b);
const moved: ExtractedFact = {...f, text: "User moved to Beijing."};
response = JSON.stringify({content: "User lives in Beijing and works remotely Friday."});
const updated = await applyDecision(b, moved, {operation: "UPDATE", target: "M1"}, {...context, fact_index: 1}, deps);
assert.match(updated.active[0].content, /Friday/);
assert.match(c.active[0].content, /Shanghai/);
assert.match(b.active[0].content, /Shanghai/);
assert.equal(initial.events.length, 0);
assert.equal(archived.active.length, 0);
assert.deepEqual((await candidates(updated, moved.text, deps)).map(m => m.id), ["M1"]);
response = JSON.stringify({content: f.text});
const returned = await applyDecision(updated, {...f, text: "User has moved back to Shanghai."}, {operation: "UPDATE", target: "M1"}, {...context, fact_index: 2}, deps);
assert.equal(returned.active[0].content, f.text);
const tentative: ExtractedFact = {...f, text: "User may move to Paris next year.", kind: "tentative"};
const withTentative = await ingestFact(returned, tentative, {...context, fact_index: 3}, deps);
const beforeNoop = requests.length;
const nooped = await applyDecision(withTentative, tentative, {operation: "NOOP", target: "NONE"}, context, deps);
assert.equal(requests.length, beforeNoop);
assert.equal(nooped.active[0].content, f.text);
assert.equal(nooped.events[1].kind, "tentative");
const deleted = await applyDecision(nooped, f, {operation: "DELETE", target: "M1"}, context, deps);
assert.equal(deleted.active.length, 0);
assert.equal(deleted.events.length, 2);
assert.equal(requests.length, beforeNoop);
assert.deepEqual(await applyDecision(nooped, f, {operation: "UPDATE", target: "M99"}, context, deps), nooped);
response = JSON.stringify({answer: "Shanghai"});
const answer = await answerFromState(nooped, {question: "Where do I live?", question_date: context.timestamp}, deps);
assert.equal(answer.answer, "Shanghai");
assert.equal(answer.retrieved.length, 3);
const answerRequest = requests.at(-1)!;
assert.ok(!answerRequest.messages[1].content.includes('"turns"'));
response = JSON.stringify({facts: [{...f, source_turns: [1]}]});
await assert.rejects(extractSession({timestamp: context.timestamp, turns: [{role: "user", content: "Hello"}, {role: "assistant", content: f.text}]}, deps), /source turns/);
response = JSON.stringify({facts: [f]});
const leaked = {timestamp: context.timestamp, turns: [{role: "user" as const, content: f.text}], question: "SECRET_QUESTION", answer: "SECRET_GOLD"};
await extractSession(leaked, deps);
assert.ok(!requests.at(-1)!.messages[1].content.includes("SECRET"));
response = JSON.stringify({facts: []});
assert.deepEqual(await extractSession(leaked, deps), []);
response = JSON.stringify({answer: ""});
await assert.rejects(answerFromState(createMemoryState(), {question: "Unknown?", question_date: context.timestamp}, deps), /nonempty answer/);
assert.deepEqual(await applyDecision(nooped, f, {operation: "UPDATE", target: ""}, context, deps), nooped);
assert.deepEqual(await candidates(createMemoryState(), "Anything", deps), []);
const extractAudit = auditExtraction({timestamp: context.timestamp, turns: [{role: "user", content: "I may move to Paris next year."}]}, [{text: "User lives in Paris.", source_turns: [0], kind: "current"}]);
assert.ok(extractAudit.facts[0].lexical_review_flags.includes("source_uncertainty_cue_absent_in_output"));
assert.equal(extractAudit.facts[0].exact_supporting_turns[0].content, "I may move to Paris next year.");
const writerAudit = auditWriter(f.text, moved.text, {operation: "UPDATE", target: "M1"}, "User lives in Beijing.");
assert.ok(writerAudit.target_clauses_to_check_for_unrelated_attribute_loss.some(c => c.target_only_words_absent_in_output.includes("friday")));
assert.equal(auditRetrieval(answer.retrieved).archive_count, 2);
console.log("local_memory_v2: fake-only checks passed (isolation, provenance, partial update, round-trip, archive, no leakage)");
